version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-data/conf.d:/etc/nginx/conf.d
      - ./nginx-data/ssl:/etc/nginx/ssl
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: personal_manage
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql