name: Build
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: false
    - name: Install
      uses: pnpm/action-setup@v2
      with:
        version: 6.0.2
    - name: Install
      run: |
        pnpm install
    - name: Lint
      run: |
        pnpm run lint
    - name: Build
      run: |
        pnpm run build
