version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: personal_manage
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql